# Uncomment this line to define a global platform for your project


platform :ios, '8.0'

inhibit_all_warnings!

target 'MVVMModel' do


pod 'AFNetworking', '3.1.0'


pod 'YYModel', '1.0.4'
pod 'MJRefresh', '3.1.12'

end
